[env]
MEASUREMENTS_ENDPOINT = "http://192.168.132.141:5000/api/measurements"

[tasks.outdated]
workspace = false
command = "cargo"
args = [
  # run `cargo upgrade --dry-run` to check versions defined in [workspace.dependencies]
  "outdated",
  "-w",
  "--root-deps-only",
]

[tasks.test]
workspace = false
command = "cargo"
args = [
  "test",
  "--target=x86_64-unknown-linux-gnu",
  "-p",
  "tests",
  "--",
  "--nocapture",
]

[tasks.test-player]
workspace = false
command = "cargo"
args = [
  "test",
  "--target=x86_64-unknown-linux-gnu",
  "-p",
  "tests",
  "--test",
  "test-player",
  "--",
  "--nocapture",
]

[tasks.test-game]
workspace = false
command = "cargo"
args = [
  "test",
  "--target=x86_64-unknown-linux-gnu",
  "-p",
  "tests",
  "--test",
  "test-game",
  "--",
  "--nocapture",
]

[tasks.fmt]
command = "cargo"
args = ["fmt"]
workspace = false

[tasks.build-all]
env_files = ["./hub.env"]
command = "cargo"
args = ["build", "--all"]
workspace = false

[tasks.run]
env_files = ["./hub.env"]
command = "cargo"
args = ["run", "--release"]
workspace = false

[tasks.build-temperature]
env_files = ["./hub.env"]
command = "cargo"
args = ["build", "--all", "--features", "temperature"]
workspace = false

[tasks.run-temperature]
env_files = ["./hub.env"]
command = "cargo"
args = ["run", "--release", "--features", "temperature"]
workspace = false

[tasks.build-server]
workspace = false
command = "cargo"
args = [
  "build",
  "--manifest-path",
  "./axum-server/Cargo.toml",
  "--target=x86_64-unknown-linux-gnu",
]

[tasks.clippy-server]
workspace = false
command = "cargo"
args = [
  "clippy",
  "--manifest-path",
  "./axum-server/Cargo.toml",
  "--target=x86_64-unknown-linux-gnu",
  "--all",
]

[tasks.clippy-all]
env_files = ["./hub.env"]
command = "cargo"
args = ["clippy", "--all"]
workspace = false

[tasks.clippy-temperature]
env_files = ["./hub.env"]
command = "cargo"
args = ["clippy", "--all", "--features", "temperature"]
workspace = false

[tasks.clippy]
env_files = ["./hub.env"]
dependencies = ["clippy-all", "clippy-temperature"]
workspace = false

[tasks.ci-check]
dependencies = [
  "fmt",
  "build-all",
  "build-temperature",
  "build-server",
  "clippy-all",
  "clippy-temperature",
  "clippy-server",
]
workspace = false
