services:
  registry:
    image: registry:3
    ports:
      - "5002:5000"
    restart: always
    volumes:
      - ./registry-data:/var/lib/registry
      - ./config.yml:/etc/distribution/config.yml
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED=true
